# Generated by Django 3.0.6 on 2020-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=20)),
                ('animal_engname', models.CharField(max_length=20)),
                ('animal_gender', models.CharField(max_length=10)),
                ('animal_birthday', models.CharField(max_length=10)),
                ('animal_personality', models.CharField(max_length=20)),
                ('animal_sort', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_name', models.CharField(max_length=20)),
                ('fish_month', models.CharField(max_length=20)),
                ('fish_time', models.CharField(max_length=20)),
                ('fish_size', models.CharField(max_length=10)),
                ('fish_location', models.CharField(max_length=20)),
                ('fish_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fossil_name', models.CharField(max_length=20)),
                ('fossil_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insect_name', models.CharField(max_length=20)),
                ('insect_month', models.CharField(max_length=20)),
                ('insect_time', models.CharField(max_length=20)),
                ('insect_location', models.CharField(max_length=20)),
                ('insect_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_name', models.CharField(max_length=20)),
                ('painting_real', models.CharField(max_length=50)),
                ('painting_original', models.CharField(max_length=50)),
                ('painting_engname', models.CharField(max_length=50)),
                ('painting_memo', models.CharField(max_length=20)),
            ],
        ),
    ]
